# Stage 1: Build
FROM node:22 AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

COPY . .

RUN npm run build

# Stage 2: Run tests
FROM node:22

WORKDIR /app

ENV NODE_ENV test

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/test ./test
COPY --from=builder /app/jest.config.js ./
COPY --from=builder /app/tsconfig.json ./

RUN npm install --only=dev

# Run migrations and tests
CMD ["sh", "-c", "npx prisma migrate deploy && npm run test:e2e"]