version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - ${ENV_FILE}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    env_file:
      - ${ENV_FILE}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    image: ${CI_REGISTRY_IMAGE:-local}/nginx:stable
    env_file:
      - ${ENV_FILE}
    volumes:
      - /etc/letsencrypt/live/dev-api.eventhuit.io.vn/:/etc/letsencrypt/live/dev-api.eventhuit.io.vn/:ro
      - /etc/letsencrypt/archive/dev-api.eventhuit.io.vn/:/etc/letsencrypt/archive/dev-api.eventhuit.io.vn/:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network

networks:
  app-network:
    external: false
    name: ${COMPOSE_PROJECT_NAME:-bttbd}_app-network
