FROM node:22

WORKDIR /app

ENV NODE_ENV development

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install -g @nestjs/cli
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE ${APP_PORT:-8081}

CMD ["nest", "start", "--watch"]