version: '3.8'

services:
  app:
    environment:
      - APP_ENV=production
      - NODE_ENV=production
      - DEBUG=false
    restart: unless-stopped

  postgres:
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_PROD:-${DB_NAME}_prod}
    restart: unless-stopped

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: unless-stopped
